name: 8004-boilerplate

plugins:
  - name: vyper
  - name: avalanche
  - name: alchemy

default_ecosystem: avalanche


vyper:
  version: 0.4.0
  enable_decimals: true
  evm_version: shanghai   # Fuji supports Shanghai the most, but you can change this to a different EVM version if needed
  search_paths:
    - ./contracts

project:
  paths:
    contracts: ./contracts

networks:
  avalanche:
    fuji:
      # Alchemy stays your default for everything else
      default_provider: alchemy
  

# Configure the 'node' provider to use the public Fuji RPC
node:
  avalanche:
    fuji:
      uri: https://api.avax-test.network/ext/bc/C/RPC

alchemy:
  avalanche:
    fuji:
      uri: https://avax-fuji.g.alchemy.com/v2/$WEB3_ALCHEMY_API_KEY

etherscan:
  avalanche:
    fuji:
      uri: https://api-testnet.snowtrace.io/api